import Link from "next/link";
import Head from "next/head";
import { Layout } from "../components";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className={styles.main}>
        <h1 className={styles.title}>Welcome To About!</h1>
      </Layout>
    </div>
  );
}
